<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2">Customer Registration is disaled</strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p>Sorry, the new account registration is disabled. Please contact Devesh Tiwari for assistance</p>
    </div>
</div>
